document.writeln("<li><a class=\"xdhbg\" href=\"\/wnl\"><div class=\"xdh_img xico1\"><\/div><div class=\"xdh_bt\">万年历<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/shouji\"><div class=\"xdh_img xico2\"><\/div><div class=\"xdh_bt\">手机归属地查询<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/kuaidi\"><div class=\"xdh_img xico3\"><\/div><div class=\"xdh_bt\">各类快递查询<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/youbian\"><div class=\"xdh_img xico4\"><\/div><div class=\"xdh_bt\">邮编查询<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/ditu\"><div class=\"xdh_img xico5\"><\/div><div class=\"xdh_bt\">中国\/世界地图<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/tel\"><div class=\"xdh_img xico6\"><\/div><div class=\"xdh_bt\">常用电话号码<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/sfz\" ><div class=\"xdh_img xico7\"><\/div><div class=\"xdh_bt\">身份证号码查询<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/yiyuan\" ><div class=\"xdh_img xico8\"><\/div><div class=\"xdh_bt\">全国著名医院查询<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/time\" ><div class=\"xdh_img xico9\"><\/div><div class=\"xdh_bt\">标准北京时间<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/sx\"><div class=\"xdh_img xico10\"><\/div><div class=\"xdh_bt\">生肖查询<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/ycq\"><div class=\"xdh_img xico11\"><\/div><div class=\"xdh_bt\">预产期自测<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/aqq\" ><div class=\"xdh_img xico12\"><\/div><div class=\"xdh_bt\">女性安全期测算<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/nannv\"><div class=\"xdh_img xico13\"><\/div><div class=\"xdh_bt\">生男生女<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/zhongcaoyao\"><div class=\"xdh_img xico14\"><\/div><div class=\"xdh_bt\">中草药大全<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/chaodai\"><div class=\"xdh_img xico19\"><\/div><div class=\"xdh_bt\">中国朝代表<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/huafei\"><div class=\"xdh_img xico20\"><\/div><div class=\"xdh_bt\">手机话费查询<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/tv\"><div class=\"xdh_img xico21\"><\/div><div class=\"xdh_bt\">电视节目<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/today\"><div class=\"xdh_img xico22\"><\/div><div class=\"xdh_bt\">历史上的今天<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/jiufang\" ><div class=\"xdh_img xico25\"><\/div><div class=\"xdh_bt\">酒方大全<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/zhoupu\" ><div class=\"xdh_img xico17\"><\/div><div class=\"xdh_bt\">营养粥谱<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/yanfang\" ><div class=\"xdh_img xico16\"><\/div><div class=\"xdh_bt\">民间验方<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/pianfang\"><div class=\"xdh_img xico23\"><\/div><div class=\"xdh_bt\">中草药偏方<\/div><\/a><\/li>");
document.writeln("<li><a class=\"xdhbg\" href=\"\/mingfang\"><div class=\"xdh_img xico24\"><\/div><div class=\"xdh_bt\">中草药名方<\/div><\/a><\/li>");